#define d_ban 1

#define DIALOG_PASSWORD 2
#define DIALOG_EMAIL 3
#define DIALOG_CHARACTER_NAME 4
#define DIALOG_CHARACTER_AGE 5

#define DIALOG_EDIT_DOOR 6
#define DIALOG_EDIT_DOOR_MODEL 7
#define DIALOG_EDIT_DOOR_EXIT 8
#define DIALOG_EDIT_DOOR_EXIT_HOUSES 9

#define DIALOG_EDIT_HOUSE 10
#define DIALOG_EDIT_HOUSE_DOORID 11
#define DIALOG_EDIT_HOUSE_GARAJEID 12
#define DIALOG_EDIT_HOUSE_DIRECTION 13
#define DIALOG_EDIT_HOUSE_PRICE 14
#define DIALOG_EDIT_HOUSE_LEVEL 15
#define DIALOG_MY_HOUSE 16
#define DIALOG_MY_HOUSE_DEPOSIT 17
#define DIALOG_MY_HOUSE_WITHDRAW 18

#define DIALOG_EDIT_FURNITURE 19

#define DIALOG_EDIT_MARKET 20
#define DIALOG_EDIT_MARKET_DOORID 21
#define DIALOG_EDIT_MARKET_DIRECTION 22
#define DIALOG_EDIT_MARKET_PRICE 23
#define DIALOG_EDIT_MARKET_TYPE 24
#define DIALOG_MY_MARKET 25
#define DIALOG_MY_MARKET_DEPOSIT 26
#define DIALOG_MY_MARKET_WITHDRAW 27
#define DIALOG_MY_MARKET_SELECTED_ITEM_INDEX 28

#define DIALOG_SELECT_MARKET_SELL_BUILDS 29
#define DIALOG_SELECT_MARKET_SELL_BUILDS_HOUSES 30
#define DIALOG_SELECT_MARKET_SELL_BUILDS_MARKETS 31
#define DIALOG_SELECT_MARKET_SELL_BUILDS_COMPANIES 32

#define DIALOG_SELECT_MARKET_FURNITURES 33

#define DIALOG_SELECT_MARKET_SELL_FURNITURES 45
#define DIALOG_SELECT_MARKET_SELL_FURNITURES_HOUSES 46
#define DIALOG_SELECT_MARKET_SELL_FURNITURES_MARKETS 47
#define DIALOG_SELECT_MARKET_SELL_FURNITURES_COMPANIES 48

#define DIALOG_SELECT_MARKET_SELL_HOUSES 49
#define DIALOG_SELECT_MARKET_SELL_MARKETS 50
#define DIALOG_SELECT_MARKET_SELL_SKIN 51
#define DIALOG_SELECT_MARKET_SELL_COMPANIES 52

#define DIALOG_VEHICLE 57
#define DIALOG_VEHICLE_WINDOWS 58

#define DIALOG_MY_COMPANY 80
#define DIALOG_EDIT_COMPANY 81
#define DIALOG_EDIT_COMPANY_DIRECTION 82
#define DIALOG_EDIT_COMPANY_TYPE 83
#define DIALOG_EDIT_COMPANY_PRICE 84
#define DIALOG_MY_COMPANY_INVITE 85
#define DIALOG_MY_COMPANY_INVITE_ID 86
#define DIALOG_MY_COMPANY_DISMISS 87
#define DIALOG_MY_COMPANY_DEPOSIT 88
#define DIALOG_MY_COMPANY_WITHDRAW 89
#define DIALOG_EDIT_COMPANY_DOORID 90
#define DIALOG_EDIT_COMPANY_GARAJEDOORID 91
#define DIALOG_EDIT_COMPANY_CLOTHES 92
#define DIALOG_EDIT_COMPANY_CLOTHES_MALE 93
#define DIALOG_EDIT_COMPANY_CLOTHES_FEMALE 94
#define DIALOG_CRAFT_COMPANY 95
#define DIALOG_CRAFT_COMPANY_PRODUCT 96

#define DIALOG_TRADES 115
#define DIALOG_TRADES_TO_DELIVERIED 116
#define DIALOG_TRADES_BY_TYPE 117




#define DIALOG_ITEMS_FURNITURES 0
#define DIALOG_ITEMS_SELECT_FURNITURE 1
#define DIALOG_SELL_SELECT_FURNITURE 2
#define DIALOG_SELL_SELECT_SKIN 3
#define DIALOG_SELL_SELECT_SKIN_MARKET 4
#define DIALOG_ITEMS_CRAFT 5
#define DIALOG_ITEMS_CRAFT_PRODUCT 6
#define DIALOG_ITEMS_CRAFT_PRODUCT_VEHI 7
#define CAPTION_DIALOG_TITLE ""SERVER_PRIMARY" Cental Park:"
