
// VIEW TEXTDRAWS
#define TEXTDRAWS_INVENTORY 1
#define TEXTDRAWS_DIALOG_ITEM 2
#define TEXTDRAWS_MENU 3
#define TEXTDRAWS_PHONE 4

#define TEXTDRAWS_MODEL_NONE 19382



//PROGRESS BARS
#define BAR_HUD_LIFE 1
#define BAR_HUD_ARMOR 2
#define BAR_HUD_DRUGS 3
#define BAR_HUD_HUNGRY 4
#define BAR_HUD_THIRST 5
#define BAR_HUD_URINE 6
#define BAR_HUD_FATIGUE 7
#define BAR_HUD_STRESS 8

// PLAYER
#define GENDER_MALE 0
#define GENDER_FEMALE 1


DEFINE_HOOK_REPLACEMENT(OnPlayer, OP_);

